### ISSUE TITLE
Signature verification failed; please verify account number (2148396) and chain-id (evmos_9001-2): unauthorized

### ISSUE THREAD

**Issue by dmiric** [hanchon-live/evmos-ts-wallet#1]
I tried using evmos-ts-wallet to send a transaction but I keep getting "Signature verification failed; please verify account number (2148396) and chain-id (evmos_9001-2): unauthorized". Not sure what I'm doing wrong. Is using 'https://lcd-evmos.keplr.app' rest address for this valid? Can you help me figure this out?

`
import { Wallet } from '@ethersproject/wallet'
import { createMessageSend } from '@evmos/transactions'
import {
  broadcast,
  getSender,
  LOCALNET_CHAIN,
  LOCALNET_FEE,
  MAINNET_FEE,
  MAINNET_CHAIN,
  signTransaction,
  singTransactionUsingEIP712,
} from '@hanchon/evmos-ts-wallet'

async function prepareMessage(wallet: Wallet) {

  const sender = await getSender(wallet, 'https://lcd-evmos.keplr.app')

  const fee = {
    amount: '4000000000000000',
    denom: 'aevmos',
    gas: '200000',
  }

  const txSimple = createMessageSend(MAINNET_CHAIN, sender, fee, '', {
    destinationAddress: 'evmos18s8tsg7ewqhq43lkhcyjyjermvgwvyax6ahtjn',
    amount: '1',
    denom: 'aevmos',
  })
  return { sender, txSimple }
}

; (async () => {
  const privateMnemonic = 'removed for internets'
  const wallet = Wallet.fromMnemonic(privateMnemonic)

  const msgKeplr = await prepareMessage(wallet)

  console.log(msgKeplr)

  const resKeplr = await signTransaction(wallet, msgKeplr.txSimple)

  const resMM = await singTransactionUsingEIP712(
    wallet,
    msgKeplr.sender.accountAddress,
    msgKeplr.txSimple,
  )

  console.log(resKeplr)

  const broadcastRes = await broadcast(resKeplr, 'https://lcd-evmos.keplr.app')

  if (broadcastRes.tx_response.code === 0) {
    console.log('Success sign transaction')
  } else {
    console.log(broadcastRes)
  }
})()

`

**Comment by hanchon** [comment]
Sorry I didn't get the notificacion for this issue, using `https://rest.bd.evmos.org:1317` should work fine
